name: API Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:lts-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run API tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TEST_URL: 'https://reqres.in/api'
        run: npm run test:api

      - name: Generate report
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        continue-on-error: true
        uses: peaceiris/actions-gh-pages@v4
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
