name: Run Node.js API Tests On Demand

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:lts-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Node.js tests
        env:
          api_key: ${{ secrets.api_key }}
          test_url: 'https://reqres.in/api'
        run: npm run test:api