name: API Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:lts-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm install

      - name: Run API tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TEST_URL: 'https://reqres.in/api'
        run: npm run test:api
