name: Load Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run load tests
        uses: grafana/run-k6-action@v1
        env:
          HOST: 'https://quickpizza.grafana.com'
          USER_NAME: ${{ secrets.K6_USER_NAME }}
          PASSWORD: ${{ secrets.K6_PASSWORD }}
        with:
          path: |
            ./tests/load/load-test.js
