name: Load Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: grafana/k6

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run load tests
        env:
          HOST: 'https://quickpizza.grafana.com'
        run: k6 run tests/load/load-test.js -e USER_NAME=${{ secrets.K6_USER_NAME }} -e PASSWORD=${{ secrets.K6_PASSWORD }}
