name: Android Mobile Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  android-tests:
    runs-on: macos-15-intel

    env:
      ANDROID_HOME: /Users/runner/Library/Android/sdk
      ANDROID_COMMANDLINE_TOOLS: /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Accept Android SDK Licenses
        run: |
          echo "${{ env.ANDROID_COMMANDLINE_TOOLS }}" >> $GITHUB_PATH
          yes | ${{ env.ANDROID_COMMANDLINE_TOOLS }}/sdkmanager --licenses

      - name: Run Appium Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -no-audio -no-boot-anim -camera-back none -gpu swiftshader_indirect -memory 3072
          disable-animations: true
          script: |
            npm run test:android

      - name: Upload Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: webdriverio-logs-and-screenshots
          path: |
            logs/
            errorShots/