name: Web Performance Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: sitespeed.io/sitespeed.io:25.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run web performance tests
        run: |
          chmod +x tests/web-performance/performance-check.sh
          ./tests/web-performance/performance-check.sh
