name: Web Performance Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: sitespeedio/sitespeed.io:38.1.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run web performance tests
        run: npm run sitespeed
